steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'my-cluster', '--zone', 'us-central1-a', '--project', '$PROJECT_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/final-project-team-eightteen-nodejs', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/final-project-team-eightteen-nodejs']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes/mysql-deployment.yml']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kubernetes/nodejs-deployment.yml']
images:
- 'gcr.io/$PROJECT_ID/final-project-team-eightteen-nodejs'
options:
  logging: CLOUD_LOGGING_ONLY