version: '3.8'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "myswagger"
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml

  postgres:
    image: postgres:latest
    container_name: postgres-db
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nodejs:
    build: .
    container_name: nodejs-app
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: